### ISSUE TITLE
This editor doesn't work for me

### ISSUE THREAD

**Issue by garmasword** [Attacktive/troubleshooter-editor-front-end-svelte#476]
Im sorry in advance for my ignorance, how am i supposed to use this editor? I uploaded my save file and I'm only getting 'AxiosError: Network Error'', what am I doing wrong?

**Comment by Attacktive** [comment]
Hello, @garmasword !

I'm sorry to hear that. Did you try to run the editor at https://attacktive.github.io/troubleshooter-editor-front-end-svelte, or locally?
Either way, you need [the backend](https://github.com/Attacktive/troubleshooter-editor-back-end) running.

I should've documented how to use it. My bad; I'll try to update the README soon.

**Comment by Attacktive** [comment]
@garmasword Updated the [docs](https://github.com/Attacktive/troubleshooter-editor-back-end/blob/main/README.md#%EF%B8%8Fhow-to-run).

In short, you have to run the back-end application on your computer
which the save files get uploaded and actual editing takes place.

Please let me know if you get stuck. :smiley:

**Comment by garmasword** [comment]
Yep, I'm very much stuck, maybe this editor is not for me or I'm just too dumb, I know nothing of programming and this seems...well, complex, I tried following the instructions to apparently run the so called back end, but I'm just too old and too lost, apparently I need some things called Git and OpenJDK 21, which i have absolutely no idea what those are, i tried installing this Git and it asked me a hundred questions that I have no idea how to answer, then you download the OpenJDK and it's just a folder with some files, and then, i need there are more steps...it seems making this editor work might be a pre-requisite for working with NASA, I think I'll just pass for now, but thanks for trying to help me

**Comment by Attacktive** [comment]
@garmasword Oh, I'm sorry. You must've had hard time.

I just finished setting up the cloud environment so you don't need to install anything at all.
All you have to do is a little [browser setting](https://github.com/Attacktive/troubleshooter-editor-front-end-svelte?tab=readme-ov-file#at-the-github-pages-preferred).

**Comment by garmasword** [comment]
awww man, i just went trough the struggle of watching youtube tutorials to understand how to install Git and OpenJDK, i've been doing this for like the past 2 hours

**Comment by garmasword** [comment]
Oh hell it worked! i could finally open the damn thing! thanks for simpliflying the process

**Comment by Attacktive** [comment]
Good to hear man. Hope you like it. 😉

**Comment by garmasword** [comment]
Unfortunately, it didnt work, the changes made are not saved

**Comment by garmasword** [comment]
that is exactly what i did, I uploaded the file, edit it, downloaded thew new edited one, and that new filed called ''cheated'' or something like that, i used to to replace my original save (and renamed it) but the changes are not being saved, there seems to be an issue with the editor, i tried a couple times

**Comment by garmasword** [comment]
Also, what if i want to add new items? it seems the editor allows to edit quantity, but if i add a new item, what about the item properties?

**Comment by garmasword** [comment]
Even better, you seem to know a lot, how do i move all the item table from one database to another (from one save game to another)

**Comment by Attacktive** [comment]
> that is exactly what i did, I uploaded the file, edited it, downloaded thew new edited one, and that new filed called ''cheated'' or something like that, i used it to replace my original save (and renamed it) but the changes are not being saved, there seems to be an issue with the editor, i tried a couple times

You tried to change item properties, right?
Sounds like something is broken then. Sorry about that. I'll take a closer look.

> Also, what if i want to add new items? it seems the editor allows to edit quantity, but if i add a new item, what about the item properties?

Correct. That's currently unimplemented unfortunately (and surprisingly). I'll try adding the feature after dealing with the bug above first.

> Even better, you seem to know a lot, how do i move all the item table from one database to another (from one save game to another)

Thanks for the idea. I'll consider implementing it.

**Comment by Attacktive** [comment]
The issue is fixed. (I believe)
